version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: rafa
      POSTGRES_PASSWORD: aaaa
      POSTGRES_DB: crypto_db
    volumes:
      - ./src/database/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crypto_network

  backend:
    build: ./src/backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql+psycopg2://rafa:aaaa@db:5432/crypto_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - crypto_network

  frontend:
    build: ./src/frontend
    container_name: frontend
    environment:
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
