services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: rafa
      POSTGRES_PASSWORD: 1a2b3c4d5e
      POSTGRES_DB: crypto_db
    volumes:
      - ./src/database/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crypto_network

  backend:
    build: ./src/backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - crypto_network

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - crypto_network

  pocketbase:
    build: ./src/pocketbase
    container_name: pocketbase
    volumes:
      - ./src/pocketbase/pb_data:/pb_data
    ports:
      - "8090:8090"
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
