services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: rafa
      POSTGRES_PASSWORD: aaaa
      POSTGRES_DB: crypto_db
    volumes:
      - ./src/database/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crypto_network

  backend:
    build: ./src/backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql+psy://rafa:aaaa@db:5432/crypto_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - crypto_network

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
